name: FirstProgram
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        working-directory: <path to repo>
        shell: javac
        run: ${{ secrets.PULL }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
            name: Package
            path: build/lib
              **/build/reports/
              **/build/test-results/