name: FirstProgram
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     # - uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
     # - run: mvn install:install-file "-Dfile=example.jar" "-DgroupId=com.cobra" "-DartifactId=cobra" "-Dversion=0.98.4" "-Dpackaging=jar" "-DgeneratePom=true"
     # - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp ./*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging