name: FirstProgram
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Test
        working-directory: <path to repo>
        shell: javac
        run: ${{ secrets.PULL }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.actor }}/my-image:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.actor }}/my-image:${{ github.sha }}