name: FirstProgram
on:
  push:
    branches: [master]
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
       # - uses: actions/setup-java@v4

        #- name: Setup Gradle
        #  uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

        - name: Test
          working-directory: <path to repo>
          shell: cmd
          run: ${{ secrets.PULL }}

        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: Package
            path: build/lib
              **/build/reports/
              **/build/test-results/